# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - suffacampus-api-azhan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install, build, and prune
        working-directory: apps/backend
        run: |
          npm ci
          npm run build
          npm prune --production

      - name: Create deployment package
        run: |
          cd apps/backend
          zip -r ../../deploy.zip dist/ node_modules/ package.json prisma/ -x "node_modules/.cache/*"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_07D3AC00210540BBB8A9FA28984F1A16 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9A72B9C9608C452E8341406BEC8A7320 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C3BBA0D2BA83459E9B74252429BC7C24 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'suffacampus-api-azhan'
          slot-name: 'Production'
          package: deploy.zip